### ISSUE TITLE
Padronização de ambiente dev com Vagrant

### ISSUE THREAD

**Issue by drgomesp** [iMastersDev/oportunidades#10]
Pessoal, acho interessante utilizarmos o [Vagrant](http://vagrantup.com/) para padronizar o ambiente de desenvolvimento e, eventualmente, o de staging e produção.

Dessa forma, basta criarmos uma VM padrão, com as versões do PHP, MySQL e qualquer outra ferramenta que formos utilizar.

Assim, mantemos um Vagrantfile no repositório, com as configurações de setup automáticas com Chef ou Puppet, para que qualquer um que queira contribuir com o projeto tenha o ambiente configurado pronto para desenvolver em pouquíssimo tempo.

**Comment by iannsp** [comment]
muito boa a ideia.
precisamos só de um candidato para realiza-la. ;)

**Comment by drgomesp** [comment]
Me disponho a fazê-lo, sem problema algum.

Só precisamos definir as configurações do ambiente.

**Comment by hussani** [comment]
Acho que precisamos fazer um levantamento de qual seria a melhor configuração para todos.

Começando por alguns pontos chaves:
- Sistema Operacional
- Versão do PHP
- Versão do MySQL

Eu voto por Ubuntu 12.04, PHP 5.3.1x e MySQL 5.5.

Outras sugestões?

**Comment by netojoaobatista** [comment]
Odeio Ubunto e qualquer Debian like, prefiro Fedora.

Sobre o PHP e MySQL, concordo com ambos @hussani.

**Comment by drgomesp** [comment]
Eu recomendo o CentOS pra sistema operacional.

O resto é variável por mim. (PHP prefiro o 5.4)

**Comment by alexsandro-xpt** [comment]
Show isto, qualquer um pode ter acesso a uma copia deste VM?

**Comment by netojoaobatista** [comment]
CentOS é bacana também.

**Comment by hussani** [comment]
@alexsandro-xpt a ideia é que todos os que desenvolvam tenham acesso a VM.
Produzindo no mesmo ambiente não teremos problemas de compatibilidade.

**Comment by netojoaobatista** [comment]
Bom, como o @drgomesp se prontificou a criar as VMs, podemos fechar assim:

CentOS, por ser mais _server_ que outras distros, como Ubuntu e Fedora.

Sobre o PHP e MySQL, instalamos as últimas estáveis do CentOS.

Fechamos?

**Comment by suissa** [comment]
ótima ideia!

**Comment by iannsp** [comment]
@drgomesp @netojoaobatista e galera.
pra mim, fechadissimo.
vamos nessa.

**Comment by augustohp** [comment]
Concordo, eu não ligo pro SO desde que a ISO não seja monstruosa.
porque a _issue_ foi fechada se o entregável dela é justamente um `vagrantfile` e ele ainda ñao existe no repositório?

Acho que essa task poderia ser feita tranquilamente antes do hangout. @drgomesp, você consegue preparar esse arquivo ainda hoje e fazer um pull request?

**Comment by netojoaobatista** [comment]
@augustohp, uma nova foi aberta: #14, focada no entregável. Acho que essa aqui foi fechada por se tratar de uma discussão sobre "ser ou não ser". Uma vez decidido, a #14 foi aberta para que a discussão seja mais focada no entregável, e não mais em outras possibilidades.
