### ISSUE TITLE
Login com Github

### ISSUE THREAD

**Issue by suissa** [iMastersDev/oportunidades#13]
Seria interessante que o Desenvolvedor pudesse logar com o github para montarmos um perfil do Desenvolvedor mais condizente com o que ele possui de projetos.

**Comment by henriquemoody** [comment]
O masterbranch faz isso muito bem, não sei se seria o caso @suissa

**Comment by netojoaobatista** [comment]
Duplicado => #7

Vamos manter temas iguais em uma única Issue, senão vamos nos perder.

**Comment by suissa** [comment]
Opa desculpa não li que ja tinha essa issue, sorry!
