### ISSUE TITLE
Labels do projeto

### ISSUE THREAD

**Issue by augustohp** [iMastersDev/oportunidades#2]
Caros, seria útil que as labels representassem o status do ticket, tenho algumas idéias mas não me apaixonei muito por nenhuma label em especial:
- **dev**: pronto pra desenvolver
- **bug**
- **feature**: Quando alguém quiser alguma feature, precisa de feedback do PO ou do time.
- **dúvida**: Quando alguém tiver alguma dúvida, Será que esse cara é realmente necessário?
- **in development**: tem um time (pair) trabalhando nisso agora

**Comment by henriquemoody** [comment]
Talvez fosse melhor este tópico estar na wiki, ao invés de ser uma task do Github.

**Comment by augustohp** [comment]
Mas a gente precisa primeiro definir as labels... depois de definido a gente pode jogar as definições no wiki. O que acha @henriquemoody ?

**Comment by netojoaobatista** [comment]
Concordo contigo @augustohp, primeiro definimos, depois publicamos no wiki.

**Comment by henriquemoody** [comment]
Concordo. Com relação aos labels, acho melhor utilizarmos termos que geralmente são utilizados

_Status_
- **pendente**: precisa de feedback do Product Owner/Cliente
- **aberto**: pronto pra desenvolver
- **em andamento**: tem um time (pair) trabalhando nisso agora

_Tipo_
- **bug**: Quando encontrarmos algum bug
- **feature**: Quando alguém quiser alguma feature
- **dúvida**: Quando alguém tiver alguma dúvida, Será que esse cara é realmente necessário?

**Comment by netojoaobatista** [comment]
Precisamos de um label para "não aceito".

_Status_
- **pendente**: precisa de feedback do Product Owner/Cliente
- **aberto**: pronto pra desenvolver
- **não aceito**: o PO achou que não deve ser desenvolvido nesse instante
- **em andamento**: tem um time (pair) trabalhando nisso agora

_Tipo_
- **bug**: Quando encontrarmos algum bug
- **feature**: Quando alguém quiser alguma feature
- **dúvida**: Quando alguém tiver alguma dúvida, Será que esse cara é realmente necessário?

**Comment by henriquemoody** [comment]
Eu concordo @netojoaobatista.

**Comment by iannsp** [comment]
cade o backlog? minha querida lista de desejos futuros ;)

**Comment by henriquemoody** [comment]
Neste caso o **não aceito** seria substituído pelo **backlog** ou teríamos os dois?

**Comment by netojoaobatista** [comment]
Acho que devemos ter os dois.

Teremos o backlog do produto e o backlog dos sprints, mas após o hangout, o projeto terá vida própria. Nesse sentido, o **não aceito** será importante.

**Comment by augustohp** [comment]
Um sprint pode ser uma **milestone**, podemos ter uma _milestone_ de backlog. Isso torna as labels `aberto` e `em andamento` desnecessárias.

Acho importante também especificar de quem é necessário o **feedback**: cliente ou time (po).
Fora isso, concordo com as labels definidas até então. =D

**Comment by henriquemoody** [comment]
Resumindo:

**Status**
- **pendente**: precisa de feedback do Product Owner/Cliente;
- **aberto**: pronto pra desenvolver;
- **backlog**: lista de desejos futuros;
- **em andamento**: tem um time (pair) trabalhando nisso agora;
- **não aceito**: o PO achou que não deve ser desenvolvido nesse instante.

**Tipo**
- **bug**: Quando encontrarmos algum bug;
- **feature**: Quando alguém quiser alguma feature;
- **dúvida**: Quando alguém tiver alguma dúvida.

Todos concordam?

**Comment by henriquemoody** [comment]
@augustohp, você pode fazer um resumo do seu _proposal_, como o que eu fiz acima?

**Comment by augustohp** [comment]
Podemos usar as milestones pra gerir o backlog, podemos ter mais de uma milestone de backlog e ir movendo as _issues_ de uma milestone pra outra.

Acho no fim, que cada milestone será um sprint, já criamos a milestone do primeiro sprint e uma milestone de backlog.
As que precisam de contato do po ou do cliente, ficam sem milestone, assim que tiverem alguma definição o PO pode criar uma milestone pra agrupar issues de uma mesma estória.

## Status
- **pendente-cliente**: precisa de feedback do Cliente;
- **pendente-po**: precisa de feedback do Product Owner;

## Tipo
- **bug**: Quando encontrarmos algum bug;
- **feature**: Quando alguém quiser alguma feature;
- **dúvida**: Quando alguém tiver alguma dúvida.

## Milestones
- **Backlog**
- **Rejeitadas**
- **sprint-1**

Todos concordam?

**Comment by henriquemoody** [comment]
Ok, o que podemos adotar como _todo_ e _doing_ pode ser o próprio assign da _issue_.

**Comment by netojoaobatista** [comment]
Ok!

**Comment by alexsandro-xpt** [comment]
Ficou bom!

**Comment by henriquemoody** [comment]
@wesleyvicthor, @alganet, @iannsp Precisamos do seus votos para fechar essa issue.

**Comment by wesleyvicthor** [comment]
ok

**Comment by drgomesp** [comment]
Tem como deixar em inglês?

**Comment by henriquemoody** [comment]
@drgomesp até prefiro, mas como tudo isso é voltado para a comunidade PHP do Brasil acho que inconscientemente decidimos fazer o máximo possível em português.

**Comment by netojoaobatista** [comment]
Concordo contigo @henriquemoody, tudo está sendo feito em português. Os hangouts, os comentários nas Issues, nome do projeto é .br, etc.

**Comment by henriquemoody** [comment]
Meu único adendo foi criar um label para "tarefa"
