### ISSUE TITLE
Componentes

### ISSUE THREAD

**Issue by faabiosr** [iMastersDev/oportunidades#25]
Não sei se ainda é o momento, mas acredito que seria interessante deixar defindo quais componentes serão usados nessa primeira etapa do projeto.
## Eu escolheria:

Respect/Rest
Respect/Validation
Respect/Config
Doctrine
Twig

**Comment by augustohp** [comment]
Momento ainda não é, precisamos focar primeiro "no quê" antes do "como", mas gostei das suas sugestões. =P
Acho que os primeiros componentes que utilizaremos serão:
- Composer
- PHPUnit

O resto melhor deixar aberto pra discussão durante o desenvolvimento mesmo. Ou por aqui no Github =D

**Comment by drgomesp** [comment]
PHPUnit na veia, o resto é resto.

**Comment by brunoaugusto** [comment]
Eu acho que muita gente, seja por preguiça ou falta de conhecimento, não utiliza PHPUnit.

Eu sou um triste exemplo. Ante ao exposto, não seria interessante esses testes virem após o hangout sobre PHPUnit já planejado?

**Comment by samuelmesq** [comment]
@BrunoAugusto os teste desse projeto, serão o conteúdo do Hangout.

**Comment by wesleyvicthor** [comment]
O objetivo desse hangout era justamente teste, aparentemente ta virando uma parada diferente...

**Comment by drgomesp** [comment]
@wesleyvicthor ressaltei isso lá no grupo. Não quero ver os hangouts virarem coisa diferente do que nasceram pra ser. Quero ver discussões a respeito de testes hoje, mesmo que em cima da aplicação que estamos idealizando. 

Foco é a palavra.

**Comment by netojoaobatista** [comment]
Não @wesleyvicthor, não está virando uma parada diferente. O foco do hangout será mostrar, na prática, o que são testes na vida real.

Se fossemos extritamente teóricos, ficaria muito difícil mostrar o que é um teste, como escrevê-lo e sua importância para o desenvolvimento.

Mostraremos o que significa, na prática, os 5 princípios de teste:

**F.I.R.S.T.**
- **F** => Fast => Os testes precisam ser rápidos, devemos ser capazes de rodar vários milhares de teste por segundo.
- **I** => Isolates => Os motivos das falhas precisam ser óbvios. Não adianta o teste falhar, é preciso que o motivo da falha seja óbvio, para que a correção seja simples e direta ao ponto.
- **R** => Repeatable => Os testes precisam poder ser executados quantas vezes forem necessárias, na ordem que forem necessárias.
- **S** => Self-Validating => Os testes precisam rodar por si só, sem intervenção humana.
- **T** => Timely => Os testes precisam acontecer **antes do código** => TDD.

Não basta falarmos sobre testes, precisamos mostrar na prática o que os testes representam na vida real do desenvolvedor. Por isso que acho importante que a coisa seja prática.

**Comment by wesleyvicthor** [comment]
boa.

**Comment by augustohp** [comment]
@fabiorphp Estou trabalhando em um branch com as coisas do Respect, mais como uma sugestão do que com o objetivo de _mergear_ esse cara pro **develop** depois.

Vamos ver o que acontece. Por hora estou fechando esta issue, fique atento por novos _branches_
