### ISSUE TITLE
CRUD com Observer sem conflito de Interfaces

### ISSUE THREAD

**Issue by brunoaugusto** [iMastersDev/oportunidades#27]
Esse é um problema particular [meu](http://goo.gl/lySOZ) mas acredito que valha a pena uma pincelada para quem pratica o uso das classes-base para todas as outras e ainda assim tem uma real necessidade em utilizar o _Observer_

**Comment by lcobucci** [comment]
Pelo que entendi vc tá querendo misturar um Active Record com Observer, certo?
Não vou nem entrar no mérito de não achar o melhor caminho para isto, mas acredito que isto é um "requisito" de uma história e não uma história propriamente dita.

Ou seja, seria um comentário das issues #11 e/ou #15, concorda @augustohp e @iannsp?

**Comment by brunoaugusto** [comment]
Eu tive muito trabalho em compreender e elaborar meu conjunto de classes relativas a banco de dados.

Material escasso, incompleto, confuso então fiz da maneira mais sensata que consegui. A única certeza que tenho, hoje, é que não é um ActiveRecord. :P

Meu problema maior e que me motivou a postar essa issue seria quanto à harmonia léxica do código. Eu tenho muito disso, infelizmente. Se o código não recebeu cuidado ao ser escrito, se a API dele é feia ou muito verbosa, nem dou crédito ao script/projeto.

Ademais, eu não vejo essa issue explicitamente como comentário ou complemento à #11 e/ou #15.

Indiretamente sim, pode ser bem aplicado.

P.S.: Quem coloca os Labels?

**Comment by lcobucci** [comment]
Depois de ver com calma, realmente num tem a ver com Active Record, mas tem algumas coisas estranhas a meu ver... anyway isso resolvemos no fórum e não aqui =P

**Comment by drgomesp** [comment]
Como já comentei lá no fórum, faz sentido para um _Manager_ implementar um _SplSubject_? Deixa isso pra lá mesmo, não tem relação com o projeto, ao meu ver.

**Comment by wesleyvicthor** [comment]
não entendi.

**Comment by wesleyvicthor** [comment]
@BrunoAugusto a maneira de como resolver os problemas decorrentes será de responsábilidade do pair em atividade(programando).

As issues são para:
1. Sugerir features
2. Reportar Bugs
3. Tirar dúvidas

**Comment by lcobucci** [comment]
Valeu @wesleyvicthor, era isso que quis dizer com meu primeiro comentário.

**Comment by brunoaugusto** [comment]
Caro Sr. Wesley.

Por acaso essa **issue** que visa permitir que ao objeto responsável pela atualização de um registro notifique Observers responsáveis à ele anexados para que estes realizem outras tarefas pós-update, deixa de ser uma **feature** sugerida?

Por acaso você acredita realmente ser viável e justificável um método _postUpdate()_ sem corpo, passível de ser sobrescrito, como presente em algumas versões do Zend Framework no passado, só para dar conta de tal tarefa?

Por fim, você acha mesmo que eu quero apenas chamar atenção para um problema pessoal meu ao sugerir que um recurso seja implementado no projeto? Se é útil ou não, se vai ser implementado ou não não cabe unicamente a você julgar.

@drgomesp, imagino que você seja o Daniel Gomes do fórum. Por acaso chegou a ver a resposta dada antes de comentar aqui, um local totalmente impróprio para isso?

**Comment by wesleyvicthor** [comment]
@BrunoAugusto faz assim cara, quer resolver seu problema e aprender ? Entra no meu lugar no hangout, tire suas duvidas e implemente a "tal feature" você estará trabalhando com um time de primeira acredite.

**Comment by brunoaugusto** [comment]
Eu assisto a todos os hangouts gravados 36 horas depois de feitos por indisponibilidade de horário.

E mais, obviamente, se eu iniciei um tópico no fórum é justamente porque não sei como proceder por mim mesmo.

Mas deixa quieto, sugestão dada, sugestão rejeitada, continuem vocês. Me limito à apenas assistir quietinho.
