### ISSUE TITLE
Design / Front-End da aplicação

### ISSUE THREAD

**Issue by ramon-to** [iMastersDev/oportunidades#28]
Primeiro quero parabenizar todos os envolvidos no projeto pelo ótimo trabalho que vocês vem realizando transmitindo conhecimento para toda a comunidade.

Sei que o foco deste projeto em si é mostrar como são feito os teste, mas se quisermos que a aplicação seja utilizada no "dia-a-dia" ela precisa de uma interface que facilite o acesso as funcionalidades da mesma. Vocês já tem alguma ideia em como vão organizar esta parte?

---

Bom, eu não sou designer, mas eu estava com um tempo ocioso aqui e tomei a liberdade de expressar em layers a minha visão do **ophortunidades**:

![ophortunidades](http://imageshack.us/a/img194/1093/ophortunidade.jpg)

O que acham?

**Comment by wesleyvicthor** [comment]
WOW!

**Comment by drgomesp** [comment]
WOW! (2)

**Comment by wesleyvicthor** [comment]
E expressou muito bem!

Simples, Prático, Objetivo.

Eu curti! talvez um ajuste aqui ou ali na tipografia, de qualquer forma, parabéns e valeu pela iniciativa!

**Comment by netojoaobatista** [comment]
@allmeida, mandou muito bem cara!

Mais legal que sua GUI, só sua iniciativa!

**Comment by marcelod** [comment]
Parabéns.... \o/

**Comment by samuelmesq** [comment]
@allmeida está dando "Not Found".

fiquei curioso demais para ver. :'D

**Comment by ramon-to** [comment]
Vlw pessoal, caso vocês queiram o psd é só falar.

---

@samuelmesq  atualizei o link da imagem. :)

**Comment by augustohp** [comment]
Wow!

Passa pro meu email, augusto@phpsp.org.br que eu jogo no repositório!

**Comment by augustohp** [comment]
PS: é a fonte Ubuntu no logo? Gostei dela!

**Comment by ramon-to** [comment]
@augustohp [Sansation](http://www.fontsquirrel.com/fonts/Sansation)
Vou dar uma organizada e já te mando.

**Comment by samuelmesq** [comment]
frontend a disposição o/.

<hr/>

@allmeida ficou show, parabéns.

**Comment by augustohp** [comment]
Está no _develop_ e no _master_.

**Comment by marcelod** [comment]
só para saber, será criado um backend tbm?

**Comment by Ferreiramg** [comment]
Coloca o Elefante do PHP em algum canto do layout ;P

**Comment by netojoaobatista** [comment]
O elefante do PHP já está no logo, @Ferreiramg, mas só os fortes conseguem ver.

:D

**Comment by Ferreiramg** [comment]
hsaushuahsuahush pod cre .. Tem q coloca um pros fracos tmb ue kkkkkk....

**Comment by NandoKstroNet** [comment]
fantastico!! Já vejo o sucesso da ferramenta!!

**Comment by augustohp** [comment]
Fechando a issue, o PSD já se encontra no repositório! =D
