### ISSUE TITLE
Padrões adotados.

### ISSUE THREAD

**Issue by augustohp** [iMastersDev/oportunidades#29]
Acho que é óbvio que adotaremos todas as **PSR**s, mas fora isso precisamos padronizar mais alguma coisas.
- Codaremos em inglês ou português? (Prefiro ingluês)
- Mensagens de commit em inglês ou português? (Prefiro português mais aí teremos que forçar uma configuração no git)
- Encoding dos arquivos? (Prefiro UTF-8)
- Line endings dos arquivos? (Prefiro Unix-like)

Tem mais alguma coisa que estou esquecendo?

**Comment by netojoaobatista** [comment]
- **Code** => Inglês
- **Commit** => Português, para seguir o padrão do repositório, como as Issues estão em português, as mensagens de commit ficarão melhores em português.
- **Encoding** => UTF-8
- **Line endings** => Unix Like

**Comment by drgomesp** [comment]
+1

**Comment by henriquemoody** [comment]
É, acho que isso não tem nem o que discutir, é isso mesmo, galera.

**Comment by drgomesp** [comment]
Sou a favor de seguir, estritamente, as PSR's 1 e 2, sem frescuras.

**Comment by rogeriopradoj** [comment]
Concordo!

Hora de fechar a issue?
