### ISSUE TITLE
Onde faremos deploy?

### ISSUE THREAD

**Issue by augustohp** [iMastersDev/oportunidades#3]
Temos que ter o deploy em algum lugar, temos algumas alternativas:
- Pagodabox
- PHPFog
- Azure
- Amazon

O que preferem?

**Comment by netojoaobatista** [comment]
Fico entre Pagodabox ou Amazon.

**Comment by augustohp** [comment]
Eu posso tentar configurar um deploy no Azure via Git também, podemos ter deploys em mais de um lugar....
O **Pagodabox** com um Boxfile e um push, resolvemos o problema e o funcionamento no Azure é bem parecido. =D
Na amazon eu já não sei se rola um _continuous deployment_, mas acho que é interessante nos mantermos só em ferramentas que forneçam essa opção, pelo menos para o hangout.

**Comment by henriquemoody** [comment]
Eu nunca usei o Pagodabox, no entanto creio que seja melhor para o nosso hangout, visto que na Amazon, pelo menos teremos que fazer tudo na mão....

**Comment by augustohp** [comment]
Meu único medo com o _Pagodabox_ é a conta free dele aguentar o número de acesso durante o hangout =(
Por isso eu utilizaria mais de um...

**Comment by henriquemoody** [comment]
A Amazon nesse caso seria mais interessante.
O problema seria o _continuous deployment_...

**Comment by iannsp** [comment]
+1 pagodabox 
justifico isso por ter membros no time que ja tem conhecimento do processo de deploy la, inclusive do arquivo de detalhes de configuração.

**Comment by rdohms** [comment]
Se eu puder dar a dica.

O limite free destes serviços é bem baixo.
Voces podem conversar com a ServerGrove eles estão sempre dispostos a ajudar. Ou a Microsoft.

Capistrano pra continuos deployment fecha redondo.

**Comment by kinncj** [comment]
Azure +1
O Serviço tem se mostrado bacana pra mim.

**Comment by drgomesp** [comment]
AWS Amazon, pelo amor de Deus!

Usamos o Lean para o deployment com capistrano, ou até a própria ferramenta da AWS, chamada Beanstalk.

**Comment by alexsandro-xpt** [comment]
Afinal, onde vai ser?

**Comment by augustohp** [comment]
Eu conheço os sistemas de deploy da maioria das clouds, até as não PHP... mas da Amazon eu nunca usei. Conheço o Capistrano de nome e tal, mas nunca usei. Não acho que seja impedimento, mas quanto menos coisa usarmos e mais simples deixarmos, melhor.

Vou tentar falar com o pessoal da Microsoft e da Servergroove ainda hoje e ver se temos uma resposta. Temos hoje e amanhã ainda. Realmente me preocupo com o limite free da coisa.

@drgomesp A Amazon cai no mesmo problema do Pagoda e do Azure. O limite da conta free =(
@alexsandro-xpt Ainda não sabemos =P Alguma sugestão?

**Comment by kinncj** [comment]
Em ultimo caso eu posso abrir espaço no meu Linode.

Mas eu curto o Azure... ja tive problemas com o free tier do EC2... estourei o limite de transferencias e tive que pagar 100doletas em 1 mes... joguei um proxy no EC2 para 18 usuarios aqui no trampo (eu disse 18 apenas), que por sinal são frenéticos por facebook, e me ferrei.. né não @suissa ?

**Comment by alexsandro-xpt** [comment]
@augustohp To vendo vocês falarem de conta free, o Azure tem um período 3 meses free: http://www.windowsazure.com/en-us/pricing/free-trial/

**Comment by augustohp** [comment]
Mandei um e-mail pro pessoal do PagodaBox, segue ele abaixo. Vou atualizando vocês.

```
Hi there!

I am part of "PHP Brasil Comunidades", a community of PHP developers from Brazil. It has been a good journey for you, been following and experimenting your services for some time now, since you launched and contacted me to try your product.

I am sending this e-mail because we are organizing a (Google) hangout to create an application live, and of course we need to deploy it somewhere. The application will be a simple job board, it will be done by Friday 5th of October (2 days from now). We will start deploying by 00h of the friday and in the first hours we will try to keep development going by at least 5am of the same day. After that, the "live" remote development stops and we continue in an asynchronous usual way of remote development. We are at GMT-3.

We don't really have many data to offer you, we really don't know how many people will view this and use the service on a daily basis. Other hangouts we do usually have 2.000 views in a week, during live recording we have form 100 to 200 people watching. As we still do not have the application, it is difficult for me to tell what could handle this people, the only sure I have is that no free tier will handle requests during the first hours of development, and as we will be live; that will be quite a sad situation =P

We have couple of options besides all the free accounts on many different cloud services, but my first option is really you!
You could help us in some kind of way? Of course all the development is Open Source, we are still deciding the license.
I am willing to work with you more times, despite the answer of this e-mail. =D
Let us know what we can do for you also! Thanks for you attention and keep awesome!

PS: Development and brainstorm is being made in github (in portuguese, sorry for that). https://github.com/iMastersDev/oportunidades
```

@rdohms Quem é melhor falar com o pessoal de **Azure**? Eu ou você? posso falar com o pessoal do Brasil aqui. Quanto ao **ServerGroove**, acho que você é o cara! Tem o dom?

@alexsandro-xpt  A free acount é pra uma máquina muito fraca, assim como os outros serviços. Nenhum serviço de cloud free vai aguentar mais do que umas 20 requisições concorrentes, durante o hangout acho que teremos mais que isso. =( Por isso temos que pedir algo um pouco mais parrudo.

Quem quiser, por favor contactem os demais serviços, vamos ver o que conseguimos fazer! Não tem muito segredo, mandem e-mails, entrem em contato e reportem aqui pra não mandarmos e-mail pra dois lugares diferentes. Só eveitem por enquanto a ServerGroove e a Microsoft, temos alguns canais diretos melhores com eles =D

**Comment by rdohms** [comment]
@augustohp Azure é melhor voce falar com o Vinicius por ai. ServerGrove eu posso falar, mas me diz se vão mesmo querer, coma SG a certeza é maior pro meu lado. Tem o servidor do SouPHPSP tb, podemos botar lá. Só me dizer que eu arrumo.

**Comment by alexsandro-xpt** [comment]
Quem é o Vinicius @rdohms ?

**Comment by suissa** [comment]
Pow @kinncj eu ouvia grooveshark todo dia mano =p

**Comment by augustohp** [comment]
@alexsandro-xpt O Vinicius Souza é o cara da _community_ e _interop_ da Microsoft Brasil. Eu dou uma ligada pra ele agora a noite @rdohms e atualizo essa _issue_. Aí startamos com a _ServerGroove_.

Status do **PagodaBox**: Encaminharam o pedido pra equipe de engenharia. Waiting.

**Comment by alexsandro-xpt** [comment]
@augustohp Suspeito de quem seja. O representante do Azure no Brasil é Luciano Condé mas só conversei com ele uma vez.

**Comment by augustohp** [comment]
Não sei se o Condé se prontificaria a ajudar mais do que o Vinicius. Pessoalmente, prefiro conversar com o Vinicius mesmo e ele fala direto com o Condé ou com alguém que consiga ceder isso pra gente. Mas provavelmente teremos a resposta só amanhã.

**Comment by alexsandro-xpt** [comment]
É o que eu imaginei mesmo.

**Comment by drgomesp** [comment]
O PagodaBox é muito legal, mas tem limitações, como bem lembrado pelo @augustohp.

Ainda assim sugiro um deploy simples com capistrano em um EC2 da Amazon.

Integração contínua fica fácil assim, basta subir um Jenkins lá mesmo, na mesma ou em outra instância.

**Comment by augustohp** [comment]
As contas **free** de todos os serviços são inúteis pra gente. Ao optar por capistrano, prefiro fazer o deploy em um server dedicado que eu tenho e que outros tem. Eu realmente gostaria de um deploy com o menor overhead possível, instalar um componente, configurá-lo especificamente pra um serviço é um overhead bem maior do que simplesmente fazer um push ou manter um arquivo específico para o serviço.

Mantendo as coisas o mais simples possível aumentamos bastante os possíveis contribuidores. Não sou contra o Capistrano e adotaria ele rapidamente. Mas optaria por opções muito mais simples, principalmente no primeiro momento.

**Comment by drgomesp** [comment]
@augustohp concordo com você, porém não vejo nada mais simples que o capistrano em um EC2 neste momento. Mas isso é uma limitação minha de conhecimento. Estou aberto a quaisquer novidades nesse quesito.

P.S.: Sem dúvida, o Pagoda facilitaria neste caso, porém temos de pensar em migrations da base de dados. Não tenho certeza se o Pagoda oferece este recurso. Com capistrano, temos isso de forma simples.

**Comment by augustohp** [comment]
Pra migração de bancos temos diversas ferramentas, podemos usar o Capistrano, o Ant, o Phing, o Make ou um script PHP mesmo. Temos diversas soluções pro mesmo problema, como não temos o problema ainda (sequer temos o código) acho que é essencial nos focarmos nas soluções mais imediatas do que em soluções pra problemas que ainda não temos.

O deploy na maioria dos serviços de coud hoje já rola com um simples `git push`, na minha opinião mais simples que o Capistrano. A maioria dos serviços de could também oferece um serviço de post-build, mas que dependendo de como a aplicação for feita, nem é necessário. =D

**Comment by drgomesp** [comment]
+1, muita informação relevante pra 2 parágrafos. =D

Migração fica pra um segundo momento.

Já o deploy, Pagoda na veia.

**Comment by kinncj** [comment]
Se não tivermos feedback rápido pra amanhã, Sobe no linode msm... mais facil(pois eu tenho, @augustohp tem N pessoas tem) e nada que um hook não sirva pro deploy (ou até mesmo o directory_root estar apontado na master) ;)

**Comment by diegoholiveira** [comment]
Porque não usar o doctrine migrations para a migração de banco? Eu estou usando ele com sucesso em um projeto.

Sobre o deploy, eu não conheço o capistrano, mas o Fabric é perfeito, principalmente porque ele dá liberdade de adequar seu deploy a qualquer vendor e qualquer arquitetura.

**Comment by augustohp** [comment]
Deploy no [PagodaBox](https://pagodabox.com/) enquanto a aplicação ainda estiver em desevolvimento.
