### ISSUE TITLE
Definir Product Owner

### ISSUE THREAD

**Issue by augustohp** [iMastersDev/oportunidades#4]
No hangout da _scrum meeting_ definimos o @iannsp , no fim acho que essa issua é mais pra formalizar isso. Todos de acordo?

PS: sim, sabemos que ele é gordo.
PPS: sim, sabemos que ele fará várias gordisses.

**Comment by netojoaobatista** [comment]
O @iannsp tem até quinta para entrar na "medida certa".

**Comment by henriquemoody** [comment]
+1 @iannsp

**Comment by augustohp** [comment]
+1 pra medida certa!

**Comment by caferrari** [comment]
+1

**Comment by alganet** [comment]
+1 cheguei agora

**Comment by drgomesp** [comment]
+1

**Comment by netojoaobatista** [comment]
Bom, acho que fechou, né?

@iannsp é nosso PO

**Comment by iannsp** [comment]
fico lisonjeado :)
saibam que no meu mandato nao vai haver fome e buscaremos a paz mundial. kkkk
- "caveira meu capitão."
- "entao senta o dedo!!!"
