### ISSUE TITLE
Remoção do bin/phpunit e composer.lock

### ISSUE THREAD

**Issue by netojoaobatista** [iMastersDev/oportunidades#41]
Pessoal, estou removendo o composer.lock por causa daquele problema que tivemos ontem. Acho melhor deixar o diretório de trabalho limpo, para que o pessoal possa usar o `composer.phar install` e configurar as coisas localmente.

**Comment by wesleyvicthor** [comment]
justo.

**Comment by londerson** [comment]
Maneiro
