### ISSUE TITLE
Quebra teste no DataAccessTest 

### ISSUE THREAD

**Issue by marcusesa** [iMastersDev/oportunidades#42]
@netojoaobatista o testInsertPosition não poderia ser quebrado em dois cara, ou seja,
testInsertPosition = testa o metodo insert do objeto Position
e depois teriamos
testGetById = testa o metodo getById  do objeto Position

eu sei que você já aproveitou o id do registro que acabou de inserir,
mas depois quando o teste falhar acho seria mas claro ter eles separados.

**Comment by netojoaobatista** [comment]
A questão do teste é que ele é isolado. Se eu separar o `getById` do `testInsertPosition`, o `getById` não retornará nada, uma vez que a tabela é destruída.

Adicionei 2 novos testes, `testGetByIdWithAnInvalidArgument` para testar um argumento inválido e o `testGetByIdWithAnInvalidID` para testar um ID inexistente.

**Comment by marcusesa** [comment]
É cara como o id só é retornado pelo método insert não daria pra fazer algo como:

``` php
public function testGetById($objectPosition){
        $dataAccess = new DataAccess($this->pdo);

        $retrievePosition = $dataAccess->getById($objectPosition->getId()); // metodo que nao existe getId()

        $this->assertInstanceOf('Ophportunidades\Entity\Position', $retrievePosition);
        $this->assertTrue($retrievePosition == $objectPosition);
}
```

Os dois novos testes testGetByIdWithAnInvalidArgument e testGetByIdWithAnInvalidID achei que esta ótimo.

Obs: pessoal não consigo colocar a label Dúvida.

**Comment by netojoaobatista** [comment]
Então @marcusesa, se eu extrair o `getById` do `testInsertPosition`, o `getById` retornará um conjunto vazio, uma vez que o `tearDown` destroi a tabela assim que o `testInsertPosition` termina. 

Nesse seu exemplo, quem vai passar o `$objectPosition` para o `testGetById`, um `@dataProvider`? E mesmo que um `@dataProvider` lhe passe esse `$objectPosition`, o `getById` vai sempre disparar um `RuntimeException` (já que a tabela está vazia).

**Comment by marcusesa** [comment]
@netojoaobatista até pensei em um dataprovider cara, mais eu acho que você tem razão como estamos trabalhando com throw exception pra casos de falha os testes **testInsertWithNullPositionShouldThrownAnException** e **testGetByIdWithAnInvalidArgument** já cobrem bem.

Por mim já esta encerrada essa issue.
