### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by paulofernandesjr** [iMastersDev/oportunidades#44]
Opa!
Galera nem sei se é aqui que posta esse tipo de coisa, mas só vamos fazer commits quando os testes passarem... se não complica a vida do pessoal.
Atualizei os arquivos e tem um teste dando erro.
Sacanagem isso :(

**Comment by drgomesp** [comment]
Qual o teste?

**Comment by wesleyvicthor** [comment]
@paulofernandesjr você sobe aplicações para produção sem teste ?

Sim, teste quebrado deve ser solucionado, não deve ser aceito PRs com testes quebrados...

Futuramente isso ficará claro na build do projeto, build quebrada o responsável por quebra-la deverá corrigir. TVN.

Caso haja duvidas com algum teste, poste-as.

**Comment by paulofernandesjr** [comment]
Não @wesleyvicthor é que fui rodar os testes e tava dando erro.
Ai imaginei que alguém tivesse subido com bug.
Falei com o @netojoaobatista e ele me explicou o que fazer :)

**Comment by wesleyvicthor** [comment]
boa.

**Comment by alexsandro-xpt** [comment]
Qual era o erro @paulofernandesjr ?

**Comment by paulofernandesjr** [comment]
dava class not found

**Comment by augustohp** [comment]
Qual era o erro @paulofernandesjr (qual classe estava faltando)? E como você corrigiu?

**Comment by paulofernandesjr** [comment]
Eu expliquei acima o problema.
Esse erro bizarro dava não sei porque, mas eu atualizei tudo e funcionou

2012/10/15 Augusto Pascutti notifications@github.com
