### ISSUE TITLE
Código das entidades.

### ISSUE THREAD

**Issue by andreyvital** [iMastersDev/oportunidades#46]
Galera, não queria interferir mas, no **meu** conceito, é correto fazer validação dentro das entidades? estas não deveriam somente representar os dados?

Ficou meio estranho pra mim :(
Abraços.

**Comment by drgomesp** [comment]
Eu acho que depende do que você precisa.

Se necessitamos que as entidades tenham essas validações, então elas deverão ter.

Ao meu ver, não tem nada de mais.

**Comment by andreyvital** [comment]
Ok; se possível, coloca a label aí, porque eu não tenho acesso.

**Comment by drgomesp** [comment]
Tá adicionada a label.
