### ISSUE TITLE
Páginas no Wiki

### ISSUE THREAD

**Issue by paulofernandesjr** [iMastersDev/oportunidades#49]
Opa!
Eu fiz uma página para configurar no Windows, vocês acham isso útil?

https://github.com/iMastersDev/oportunidades/wiki/Configurando-o-Ambiente

**Comment by drgomesp** [comment]
@paulofernandesjr, até acho útil, porém dispomos da ferramenta Vagrant, que facilita ainda mais a criação de um ambiente de desenvolvimento, especialmente na plataforma Windows.

Vou criar essa wiki hoje ou amanhã, explicando como subir a VM, coisa de 10 minutos, e ter um ambiente normalizado com as versões exatas necessárias de cada pacote utilizado na aplicação.

De qualquer forma, valeu pela contribuição!

**Comment by rogeriopradoj** [comment]
Poxa, acho que vale os dois.

@paulofernandesjr , não quer dar uma lida http://vagrantup.com/.

Lá tem o instalador do Vagrant para windows.

**Comment by netojoaobatista** [comment]
Exato @rogeriopradoj, valem os dois.

É tão importante mostrar como se configura o ambiente de desenvolvimento no Windows **sem utilizar** Vagrant, quanto é importante mostrar como se configura o ambiente utilizando o Vagrant.

Nosso Wiki deve ser rico em informações. Quanto mais informações tivermos, mais fácil será para as pessoas entenderem como as coisas são feitas, e mais fácil será para essas pessoas contribuírem com o projeto.

Da mesma forma, acho válido e importante termos a mesma estrutura para configuração no Linux (com e sem Vagrant) e também no Mac (com e sem Vagrant).

**Comment by augustohp** [comment]
Eu preferia centrar tudo no `README.md`, pra manter as informações concisas e independentes do _GitHub_. Já temos as _issues_, não queria deixar a documentação do projeto dependendo dele também sem necessidade.

Acham que o _readme_ vai fica gigantesco? Acho que a limitação é bacana porque nos força a manter ele sempre simples.

**Comment by augustohp** [comment]
Up.

**Comment by victorferreira** [comment]
acho que vamos de 'README.md'  mesmo.

**Comment by augustohp** [comment]
Perfeito. Odeio documentação presa em vários lugares... ainda mais indisponível offline. :palm_tree:
