### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by augustohp** [iMastersDev/oportunidades#5]
Nosso projeto precisa urgente de um README lindão usando **Markdown** descrevendo o que faremos ou o que dissemos até agora no vídeo.

Links para os outros hangouts, posts ou tudo mais também seriam interessantes.
Pra não sujar o controle de versão, vamos definir o que queremos no README?

**Comment by kinncj** [comment]
- Sobre o projeto
- Como postar oportunidades
  - Links para a wiki
- Como contribuir
  - Links para a wiki
- Donate button :p

**Comment by robsonpeixoto** [comment]
Colocar o canal do IRC onde acontece o bate papo.

**Comment by drgomesp** [comment]
Informações a respeito dos hangouts, horários e página do iMasters no Google+.

**Comment by gnuwilliam** [comment]
Atualizei o README e abri uma pull request.

O que acharam? Sugestões?

https://github.com/gnuwilliam/oportunidades

**Comment by augustohp** [comment]
@gnuwilliam Comentei no próprio pull request =D Valeu pela contribuição.
