### ISSUE TITLE
Domain-Driven Design

### ISSUE THREAD

**Issue by alexsandro-xpt** [iMastersDev/oportunidades#50]
Assisti o dally meet onde o @drgomesp sugere em mudar o diretório DataAccess para Domain.

Vi que ninguém concordou e acredito que seja pelo fato do projeto não contemplar DDD.
A ideia de usar DDD seria interessante no inicio, mas como ja tem muita coisa pronta é totalmente inviável.

Gostaria de saber do @drgomesp se ele tinha sugerido usar de fato DDD ou simplesmente mudar a o nome do diretório de DataAccess para Domain.

**Comment by drgomesp** [comment]
Como comentei lá no 4888d10901:

> Quando sugeri o namespace Domain em substituição ao DataAccess, estava falando exatamente do conceito de domínio passado pelo Eric Evans, no livro Domain-Driven Design.
> 
> O Domínio da aplicação é, sim, restrito ao problema de negócio o qual ela se propõe a resolver. Isto, porém, não transforma a aplicação inteira em parte ativa neste domínio.
> 
> A verdade da maioria dos softwares é que a parcela efetiva de código que resolve o problema inicialmente proposto a resolver é bastante pequena em comparação com o código final da aplicação.
> 
> O que quero dizer com tudo isso é que teremos boa parte de nosso código fora do domínio em que estamos trabalhando - uma aplicação que permite a publicação de oportunidades de trabalho com PHP.
> 
> Um exemplo bastante comum que vejo para demonstrar este raciocínio é a solução de problemas recorrentes em desenvolvimento de aplicações web, como a camada de persistência e a presentation-logic.
> 
> Essas duas estão, de alguma forma, ligadas ao domínio, mas não fazem, necessariamente, parte ativa do domínio em que estamos trabalhando.
> 
> A grande pergunta é: teríamos uma aplicação funcional, do ponto de vista de negócio, sem a existência das camadas de persistência ou de presentation-logic?
> 
> Eu, particularmente, gosto de poder testar o negócio da aplicação sem depender de nada disso, especialmente de uma camada de acesso a dados.
> 
> Acho que vale a discussão a respeito.

**Comment by alexsandro-xpt** [comment]
Comentei la mas não apareceu.. estranho..

veja:

Entendo @drgomesp, mas para aplicar o conceito de domínio acredito que deveríamos trabalhar desde o inicio com DDD, usando toda metodologia e patterns como o repository patterns e serviços.

Como a gente não fez nada disto, apenas mudar a namespace por mudar não seria a mesma coisa que trocar por nada?

**Comment by drgomesp** [comment]
Como comentei anteriormente, a ideia era somente dar à estrutura de namespaces um pouco mais de sentido.

**Comment by alexsandro-xpt** [comment]
Saquei, para quem não conhece DDD acho que faria pouco sentido.

**Comment by drgomesp** [comment]
Tem razão, pode fazer pouco sentido mesmo.

Porém, a reação do pessoal ao meu comentário é que foi estranha. 

O próprio Eric Evans ressalta que o domínio da aplicação é uma parcela relativamente pequena de todo o código que temos que escrever para concebê-la.

A visão do pessoal é totalmente contrária a isso.

**Comment by netojoaobatista** [comment]
Durante o desenvolvimento, nos deparamos com diversos domínios:
1. Data/Storage - Nesse domínio lidamos com armazenamento de dados. Podemos utilizar, ou não, uma linguagem de domínio específico, chamada SQL, se estivermos trabalhando com uma base relacional.
2. Presentation/View - Nesse domínio lidamos com a representação de alguma coisa. Podemos utilizar, ou não, uma linguagem de domínio específico, chamada HTML, se a representação for entregue para um browser.
3. Application Domain - É sobre esse domínio que o @drgomesp está falando. Sobre aquilo que a aplicação faz, sobre aquilo que ela pretende resolver.

O problema, contudo, é que um namespace `domain`, em qualquer aplicação que seja, **é errado**. Primeiro por estarmos lidando com N domínios durante o desenvolvimento; Segundo porque ele não descreve aquilo que está contido nele, devido a ambiguidade causada pelos N domínios envolvidos.

Outro ponto que **precisa** ser resaltado é que `DataAccess` contém apenas o que é referente ao acesso a dados. Independentemente do local onde eles estão. Aquele namespace não tem, **e jamais terá**, como objetivo, representar o domínio da aplicação. Tudo o que temos lá, é o encapsulamento do acesso a dados e uma abstração, para que a aplicação possa variar o source/target dos dados, sem que precisemos mudar como isso é feito dentro aplicação.

Segundo o princípio de design de empacotamento `CCP`, classes que mudam juntas, devem ser empacotadas juntas. Assim, como os objetos de acesso a dados mudam juntos, eles devem ficar juntos. Como o objetivo é permitir que essas mudanças não afetem o restante da aplicação, o restante da aplicação, inclusive seu domínio, devem ser empacotados **fora** da `DataAccess`.

Fico preocupado com essas confusões de termos e conceitos que as pessoas fazem. Fico preocupado porque, muitas vezes, não sei se sou eu quem não está conseguindo passar a ideia, ou se são as pessoas que não conseguem compreender o que foi passado.

Então, apenas para frisar: `DataAccess` tem como objetivo fazer **exatamente** aquilo que sua tradução diz: **acesso a dados**.

**Comment by drgomesp** [comment]
@netojoaobatista, pode ser a minha visão de `DataAccess` que seja diferente da sua, então.

Entendo por `DataAccess` uma camada que proporciona acesso a qualquer dado que esteja armazenado em um local de persistência, seja um banco de dados, um arquivo, etc. Portanto, ao meu ver, entidades nada tem a ver com `DataAccess`. Essa foi a minha preocupação quando levantei essa questão.

Imagine a seguinte situação: de agora em diante decidimos não mais utilizar uma camada de acesso a dados que já estão ou serão persistidos. Como fica a nossa aplicação? Ela perderá as entidades, por estarem _acopladas_ a um domínio da qual não fazem parte? Isso sim é que me preocupa em relação à nossa arquitetura.

Penso que devo ser capaz de remover toda `DataAccessLayer` ou `DataAccess` e continuar tendo uma aplicação funcional do ponto de vista do domínio da aplicação. E isto envolve ainda ter entidades.

Sim, quando citei o `Domain`, estava falando do domínio de aplicação, aquele que apresenta o problema que estamos tentando resolver. Nesse ponto, concordo com você, e acho que realmente tratamos com diferentes domínios ao desenvolver uma aplicação.

Mudo minha sugestão, entao, para o namespace `ApplicationDomain`, ou `BusinessDomain`, somente para não gerar mais confusões.

Todavia, ainda acredito que as entidades devem estar fora do namespace `DataAccess`.

**Comment by alexsandro-xpt** [comment]
Fico com:

> "Segundo porque ele não descreve aquilo que está contido nele."

Para virar de fato um `ApplicationDomain` algumas coisas deveram ter que ser mudada por exemplo o _acoplamento_ de namespace `DataAccess` por isto concordo com a frase do @netojoaobatista.

So que é o seguinte, se amanha a gente propagar as entidades a um serviço e dependendo deste serviço sendo REST, SOAP ou outro. A namespace `DataAccess` não pareceria ou não ficaria vinculado na entidade serializada citando alguma referencia a `DataAccess`?

**Comment by netojoaobatista** [comment]
Okay @drgomesp, agora estamos nos entendendo.

> Penso que devo ser capaz de remover toda DataAccessLayer ou DataAccess e continuar tendo uma aplicação funcional do ponto de vista do domínio da aplicação.

O fato é que aquela `Position` que está em `DataAccess` não deveria ter comportamento. Ela deveria ser um objeto sem comportamento, mas que possui identidade, para abstração do storage, de forma a permitir, por exemplo, variar de um modelo relacional, para um não relacional, que possuem armazenamentos conceitualmente diferentes.

Dessa forma, os seguintes passos devem ocorrer:
1. Uma nova `Position` deve ser criada, fora de `DataAccess`, representando o objeto do domínio da aplicação.
2. A `Position`, que está dentro de `DataAccess` deve ser renomeada para `PositionEntity`.
3. Todo o comportamento deve ser completamente removido da `PositionEntity`.
4. A validação de input deve ficar, ou na nova `Position`, ou na `BusinessLogic`

Dessa forma, a `PositionEntity` que está dentro de `DataAccess` continuaria sendo `Entity`, por possuir identidade. A `Position` que está fora de `DataAccess` seria um `ValueObject` por ter apenas valor, não ter identidade, e representar o objeto de domínio da aplicação.

**Comment by drgomesp** [comment]
Concordo com você, @netojoaobatista, com relação ao comportamento de `Position`. Também acho que a entidade deve representar uma `DataStructure` e ser desprovida de comportamento de negócio.

Isto, porém, não invalida a ideia de mover a `PositionEntity` para fora do namespace `DataAccess`, pelos mesmos motivos que citei anteriormente.

**Comment by netojoaobatista** [comment]
Fora do `DataAccess`, @drgomesp, não haverá identidade e, portanto, não se trata de `Entity`.

Existe uma diferença conceitual entre `Entity` e `Value Object`. Fora da `Data Access`, jamais teremos identidade e a `Position` será apenas um objeto de dados do domínio.

**Comment by augustohp** [comment]
Vocês tem que tomar cuidado com as discussões de vocês. Existe uma distância entre _prática_ e _conceito_, `Domain Driven Development` é um conceito bem abstrato, logo concordo quando são contra classes com o nome `Domain` em qualquer parte. Pra mim soa como querer nomear uma classe com um prefixo ou sufixo `Class`. É desnecessário.

Quanto à organização das **entidades**, eu não tenho posição definida. Concordo com o atual e concordo com entidades debaixo de outro namespace. Mas não precisamos disso agora. Temos meia dúzia de classes e estamos discutindo já um refactor antes de conseguirmos ter nosso primeiro entregável.

Ao meu ver, DDD foi utilizado. Não é porque algo não foi mencionado que foi esquecido. Fizemos um TDD bem simples no hangout também, não fizemos _refactor_ religiosamente nem explicitamos os padrões de testes em vermelho e verde. O @alganet me cobrou isso uma vez e eu nunca mais deixo de esquecer eles. =P

A discussão é sadia, mas se nos focarmos mais em _prática_ ao invés de _conceitos_, produzimos mais. E atualmente esse é nosso maior problema. De longe.

**Comment by augustohp** [comment]
1 mês se comentários, to considerando essa discussão como morta e fechando esta issue.
