### ISSUE TITLE
Rodar app

### ISSUE THREAD

**Issue by paulofernandesjr** [iMastersDev/oportunidades#51]
olá pessoal.

vi que o front já esta pronto.
O que esta faltando para exibir o front-end?

O que acham de criar uma lista de tarefas e começarmos a finalizar as coisas?

Abraço

**Comment by drgomesp** [comment]
@paulofernandesjr, acho que ainda estamos dependendo da discussão envolvendo a presentation logic, no #47.

**Comment by augustohp** [comment]
Precisamos de documentação de como rodar e contribuir no `README.md` também...

**Comment by augustohp** [comment]
Com o `Makefile` no #56 você pode instalar as dependências usando `make install` e rodar os testes usando `make test`.

Como o @drgomesp mesmo disse, estamos discutindo as coisas na issue e aqui no github. Nada te impede de forkar o projeto, e enviar um pull request com sua sugestão.

Nossas prioridades estão todas no GitHub através das milestones de versão. Por enquanto estamos no **Sprint-1**, não decidimos se usamos ou não a proposta feita na issue #47.

Esses detalhes de como trabalhos e das ferramentas que usamos podem estar documentadas no `README`. Algum candidato?

**Comment by drgomesp** [comment]
Vou colaborar nesse sentido assim que tiver um tempo disponível.

**Comment by augustohp** [comment]
Acho que ao invés de criar instruções de como rodar e manter isso (o que é uma coisa que duvido que alguém vá fazer), vamos priorizar o uso do [Vagrant](http://vagrantup.com) e assim já aproveitamos toda a documentação dele já pronta :laughing: 

Estou fechando essa issue por considerar ela uma duplicada da issue #14.
