### ISSUE TITLE
Daily Metting

### ISSUE THREAD

**Issue by henriquemoody** [iMastersDev/oportunidades#52]
Pessoal, temos que agilizar nossas reuniões diárias;
- Estabelecer um horário;
- Estabelecer tempo de duração;
- Usar um token durante a reunião;
- Estabelecer/cobrar entregáveis.

Any thoughts?

**Comment by rogeriopradoj** [comment]
O que seria um token?

Horário: 23h30 (sugestão do Wesley)
Duracao: 10 minutos, até 15 (sugestão do Augusto)

**Comment by drgomesp** [comment]
Horário poderia ser mais cedo, não? Umas 11:00h?

**Comment by netojoaobatista** [comment]
O ponto do horário, @drgomesp, é o pessoal que estuda a noite. Se for mais cedo, eles não conseguem chegar a tempo.

**Comment by paulofernandesjr** [comment]
Se o tempo for respeitado.. Acho que podemos marcar para meia noite

On Mon, Oct 15, 2012 at 9:37 AM, João Batista Neto <notifications@github.com

**Comment by augustohp** [comment]
**23:30** ou **00:00** por tranquilo.

@rogeriopradoj O _token_ seria a _permissão_ de falar

@paulofernandesjr O horário tem que ser respeitado. Se ultrapassamors, cabe a quem participar cobrar a brevidade dos demais. Óbvio, no começo iremos falhar; mas a medida que formos trabalhando, vamos melhorando.

**Comment by augustohp** [comment]
Vamos fazer isso funcionar? Acho que **diário** é demais pra todo mundo, mas e uma vez por semana?
Qual dia da semana vocês preferem? Quarta é uma alternativa bacana...
- Horário: 23h30
- Duração: 20min (objetivo de fazer em 10min)

**Comment by paulofernandesjr** [comment]
Eu prefiro as 00:00 ou 00:30 

Antes disso é bem complicado.

**Comment by augustohp** [comment]
00h ok pra mim.

**Comment by netojoaobatista** [comment]
Escolham o dia e a hora que for melhor para vocês, que para mim estará okay.

## 

João Batista Neto
Desenvolvedor engenheiro de aplicações web
1º Master Certified Professional do PayPal Brasil

2012/11/4 Augusto Pascutti notifications@github.com

**Comment by augustohp** [comment]
Até que mais alguém se manifeste, (esta) quarta 00h entnao =D

**Comment by drgomesp** [comment]
Eu prefiro antes da meia-noite, às 23h30m.

**Comment by rogeriopradoj** [comment]
0h, 07/11/2012, é isso então?

**Comment by henriquemoody** [comment]
Por mim fechou.

**Comment by rogeriopradoj** [comment]
E aí, pessoal, vamos ter encontro hoje de noite, 08/11/2012 às 23h59, ou deixa mais para a frente?

**Comment by augustohp** [comment]
Eu to desistindo das reuniões até porque as coisas estão bem complicadas pra mim também.
Acho que se mantivermos nossa comunicação aqui nas issues acabamos tendo tudo o que precisamos.

**Comment by rogeriopradoj** [comment]
Beleza, Augusto.

**Comment by rogeriopradoj** [comment]
Acredito que está a mesma situação para todos, então estou fechando a issue.
