### ISSUE TITLE
Hashtag social

### ISSUE THREAD

**Issue by augustohp** [iMastersDev/oportunidades#6]
Acho bacana definirmos uma #hashtag pra utilizarmos no twitter e em outros serviços social pra identificar as discussnoes sociais do hangout. Acho que ganharemos bastante no tracking futuro do projeto.

**Comment by henriquemoody** [comment]
+1 #devtalk

**Comment by augustohp** [comment]
#devtalk é muito global, a gente vai te muito noise no meio das pesquisas. Acho que algo único seria mais bacana.

**Comment by henriquemoody** [comment]
#hangoutdephpsobretestes

**Comment by lcobucci** [comment]
Dá pra usar algo como #phpAoVivo ou (#phpLiveCoding|#phpLive) (pra quem gosta de falá ingreis)

**Comment by RuanAragao** [comment]
#ophportunidades, uma hashtag que conta a vida do produto, desde o inicio do desenvolvimento até a utilização do mesmo =D.

**Comment by netojoaobatista** [comment]
#jamaica

**Comment by henriquemoody** [comment]
Concordo com o @RuanAragao 

+1 #ophportunidades

**Comment by netojoaobatista** [comment]
Por mim, fechado em #ophportunidades

**Comment by iannsp** [comment]
acho que nao temos nem como dar continuidade na discussão hahaha
a hashtag vai sim, ser o nome do produto mesmo.
pra mim, fechado.
