### ISSUE TITLE
Integração com o Facebook Social Jobs Partnership

### ISSUE THREAD

**Issue by victorferreira** [iMastersDev/oportunidades#61]
Pessoal, vi hoje que o Facebook lançou uma ferramenta de listagem de jobs. Funciona com alguns parceiros lá dos Estados Unidos, mas eu pensei que se houver uma API aberta a gente podia divulgar as nossas vagas do OPHPortunidades por lá e com isso dar uma maior visibilidade ao serviço.

http://www.facebook.com/socialjobs

**Comment by augustohp** [comment]
Sem dúvida é uma funcionalidade interessante, mas focaria nesse tipo de integração somente com a idéia e a modelagem de dados madura do nosso lado. Mas muito bom já estudar essa integração.
