### ISSUE TITLE
Retomar o desenvolvimento

### ISSUE THREAD

**Issue by victorferreira** [iMastersDev/oportunidades#64]
Pessoal, alguém aqui tem algum interesse em retomar o desenvolvimento da ferramenta?

Não sei vocês, mas eu me incomodo com o post de vagas no grupo do PHPBrasil no facebook. Aliás, o surgimento da idéia original de ter o Ophportunidades era eliminar a necessidade de posts desse tipo por lá.

Eu acompanhei o hangout na época e olhando o estado do código acho que não estamos longe de termos a aplicação funcionando. Até a interface já foi feita!

E aí, alguém?

**Comment by danizord** [comment]
Tô dentro :+1:

**Comment by victorferreira** [comment]
@danizord o/

@augustohp, você tem alguma posição quanto ao deploy. Vi que havia uma discussao em torno disso e que você tinha tomado a frente.

**Comment by victorferreira** [comment]
@danizord Qual seria a prioridade agora?

**Comment by augustohp** [comment]
O deploy acho que o esquema é usar o [PagodaBox](https://pagodabox.com/) por enquanto, depois com o negócio finalizado a gente vê o que faz.

Acho que a prioridade é atualizar todas as issues com o que a gente tem no **develop**, e ir atualizando as issues. Eu sou suspeito pra falar, mas gosto bastante do branch do `respect` da issue #57 mas topo qqr coisa.

Nossa prioridade é ter um entregável, que é a postagem e listagem de jobs. Em cima disso, a gente evolui em outras necessidades. O que acham?

**Comment by augustohp** [comment]
Existe a milestone 1 que temos que fechar. Acho que é um ótimo começo. ;)

**Comment by victorferreira** [comment]
@augustohp Respect +1 o/

**Comment by augustohp** [comment]
:relieved:

**Comment by augustohp** [comment]
Vou fechar essa issue, pra gente poder ir interagindo e agilizando as coisas nas issues da milestone1.
