### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by kinncj** [iMastersDev/oportunidades#8]
Qual será adotado ?

Sugestão:
- branches:
  - dev
    - feature
    - release
  - master
    - release

**Comment by kinncj** [comment]
podemos ainda ter um flow só para oportunidades ?

**Comment by drgomesp** [comment]
[Gitflow](https://github.com/nvie/gitflow), please

**Comment by kinncj** [comment]
@drgomesp +1 
Estamos utilizando aqui, e definindo um branching model não necessáriamente precisamos usar a ferramenta git-flow, ela fica opcional.

e ainda acredito em um fluxo para conteúdo (ou um branch para atualização/postagem de conteúdo)

**Comment by drgomesp** [comment]
@kinncj o gitflow é baseado [neste branching model](http://nvie.com/posts/a-successful-git-branching-model/).

Sugiro utilizarmos, nem que seja o conceito.

**Comment by kinncj** [comment]
@drgomesp Sim, já entendi o ponto e inclusive disse que o utilizo, mas tem mais N coisas para definir, bem como a convenção de nomes dos branches, se vamos utilizar o support, hotfix e etc... não apenas escolher sem definir.

e novamente: acredito em um fluxo para conteúdo (ou um branch para atualização/postagem de conteúdo)

**Comment by iannsp** [comment]
o importante é ter padrão.
imagino que os votos para o gitflow vao ser unanimes mesmo.
dai, é sentar e ver como vai ser ele dentro da situação de stress que vai ser a coisa toda funcionando live, remote, com interações da galera, com narração do galvão bueno e cheer leaders.

**Comment by wesleyvicthor** [comment]
Acho que deveriamos focar na entrega do produto, features, qualidade/arquitetura, TESTES que é o foco desse hangout, e não encher de ferramentas para um desenvolvimento inicial de 4 horas, essas ferramentas poderão vir conforme o crescimento do projeto e a cooperação dos "clientes".

**Comment by drgomesp** [comment]
+1 @wesleyvicthor

**Comment by suissa** [comment]
+1 @wesleyvicthor

**Comment by henriquemoody** [comment]
+1 @wesleyvicthor

**Comment by alexsandro-xpt** [comment]
+1 @wesleyvicthor

**Comment by kinncj** [comment]
@wesleyvicthor não precisamos da ferramenta, apenas de um workflow :)
+1

**Comment by netojoaobatista** [comment]
Okay pessoal, fechamos em _não usar ferramenta_ e, em vez disso, **usar apenas um workflow**.

Dessa forma, voltamos para o primeiro comentário: "Qual será adotado ?" e, nesse caso, concordo com a sugestão do @kinncj

**Comment by henriquemoody** [comment]
+1

**Comment by augustohp** [comment]
Curto a idéia, e usaria o workflow do git-flow mesmo.
- **develop** Merge dos branchs de feature
- **master** Deploy desse cara
- **feature-valueObjects** Um entregável criado a partir do _develop_ e que será mergeado com o _develop_
- **bug-travis** Branch criado a partir do _master_ ou _develop_, com merge da onde ele veio. Caso o merge seja feito no master, ele precisa ir pro develop também.

Não acho que a gente precise dos _release_, vamos atacar um _continous deployment_ e ser felizes. Acho que se foi no **master** tem que ter **deploy**.

**Comment by alganet** [comment]
Eu sou noob no git flow. Queria estar bem seguro sobre ele antes de trabalhar com vocês nesse sistema. Alguém me explica como integração contínua funciona com git-flow?

**Comment by augustohp** [comment]
Não tme nada que defina onde e como usar IC no git-flow, mas na teoria ao fim de cada _feature_, antes de fazer o merge devolta pro **master** ou pro **develop**, deveria rolar uma checagem pra garantir que não existe nenhum teste quebrado.

Mas isso é totalmente por conta do desenvolvedor que fará o merge, a ferramenta e o workflow não tangem isso =(

**Comment by alganet** [comment]
Ah eu entendo que não existe nada que defina e tal. Tentamos usar aqui no Yahoo!, mas acabou ficando improdutivo porque passavamos muito tempo fazendo merge das features, então imagino que fizemos algo de errado (a integração no final não era nada contínua). Queria algum exemplo prático, algum case study mesmo.

**Comment by kinncj** [comment]
Exatamente oq o @augustohp disse.
Além do developer testar e rodar seus testes, axo q nesse nosso caso o **travis** (ou qqr coisa) poderia rolar no nosso branch develop a cada merge de feature pro develop ... não levaria nenhum tempo para integrarmos isso.

**Comment by kinncj** [comment]
@alganet em breve talvez teremos um _Case report_ bacana, eu + @augustohp + @henriquemoody + outras pessoas estamos trabalhando para implementar aqui na Dafiti

**Comment by alganet** [comment]
O Travis é sussa, mas não garante eficiência no merge. Meu medo é ficarmos 1h no Hangout fazendo merge de branches que demoramos menos de 1h pra criar :S

**Comment by kinncj** [comment]
Acredito que a ideia é a galera trampar no mesmo branch(da feature) e no final empurrar ela pro develop, é um merge como se fosse pro master... não acredito que tenha problemas... possiveis problemas apenas com varios branches sendo empurrados para o develop, ai sim pode ter conflitos e tudo mais

**Comment by augustohp** [comment]
@alganet Concordo que é improdutivo. O _branching model_ de features é bem contra produtivo. Nos meus testes aqui na Dafiti o único ganho (que pra gente é bem grande) é a uniformidade dos _merges_. Mas de fato, se você tem uma equipe que lida bem com os merges e o próprio git, não tem porque não fazer direto no **develop**. Até mesmo porque só um par vai codar por vez no develop.

O que faremos então? Direto no develop?

**Comment by kinncj** [comment]
Conversando aqui com o @augustohp , realmente se formos pensar em Agile, ficaria inviável... caminhos a mais, barreiras a mais.

**Comment by alexsandro-xpt** [comment]
Só um par vai codar por vez no **develop** mesmo?
Não limitar muito não?
Talvez valeria apena tentar achar um meio satisfatório para estes merges, sei la :P

**Comment by augustohp** [comment]
@alexsandro-xpt Pro hangout será só um par. Depois o próprio _GitHub_ e os forks vão fazer o trabalho. Enquanto tivermos menos de 15 pessoas contribuindo acho que esse caminho é sustentável =P

Não queria dificultar muito a vida dos novos contribuidores. Acho que isso é bem essencial.

**Comment by alganet** [comment]
No Hangout acho que temos que fazer um par por vez. O objetivo principal é ensinar, não criar um app. Se o cara não puder ver algo que está em desenvolvimento de maneira clara, com algum de nós explicando o que tá sendo feito, não será muito útil pro aprendizado.

Depois do Hangout no entanto pode ser que queiramos continuar com o projeto, aí talvez um branching model seja bastante apropriado.

**Comment by augustohp** [comment]
@alganet +1

**Comment by netojoaobatista** [comment]
Perfeito @alganet!

**Comment by alexsandro-xpt** [comment]
Maravilha, isto ai mesmo, durante Hungout um par no máximo para dar para acompanhar.

**Comment by kinncj** [comment]
@alganet +1
